# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180201_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='dese',
            new_name='desc',
        ),
    ]
